- name: Running NPM install
  npm: 
    path: /tmp/node-js-getting-started

- name: populate /etc/environment
  lineinfile:
    path: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value}}"
  with_items: 
    - { key: 'DATABASE_URL', value: 'postgresql://{{ db_user }}:{{ db_password }}@{{ db_ip }}:5432/{{ db_name }}' }
  become: yes

- name: "Install forever (to run Node.js app)."
  npm: name=forever global=yes state=present

- name: "Check list of Node.js apps running."
  command: forever list
  register: forever_list
  changed_when: false

- name: "Stop example Node.js app."
  command: forever stop /tmp/node-js-getting-started/index.js
  when: "forever_list.stdout.find('/tmp/node-js-getting-started/index.js') >= 1"

- name: "Check list of Node.js apps running."
  command: forever list
  register: forever_list
  changed_when: false

- name: "Start example Node.js app."
  command: forever start /tmp/node-js-getting-started/index.js
  when: "forever_list.stdout.find('/tmp/node-js-getting-started/index.js') == -1"
  environment:
    DATABASE_URL: postgresql://{{ db_user }}:{{ db_password }}@{{ db_ip }}:5432/{{ db_name }}