- name: Create a PostgreSQL DB server
  hosts: postgres
  vars_files:
    - group_vars/postgres.yaml
  roles:
    - postgres

- hosts: node
  vars_files:
    - group_vars/postgres.yaml
  roles:
    - role: node
    - role: app